// <auto-generated />
using System;
using FashionStore.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FashionStore.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250316200554_addDataSeedManWoman")]
    partial class addDataSeedManWoman
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FashionStore.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("FashionStore.Models.CartItem", b =>
                {
                    b.Property<int>("CartItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CartItemID"));

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CartItemID");

                    b.HasIndex("ProductID");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("FashionStore.Models.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryID"));

                    b.Property<int>("CategoryHeaderID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryID");

                    b.HasIndex("CategoryHeaderID");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("FashionStore.Models.CategoryHeader", b =>
                {
                    b.Property<int>("CategoryHeaderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryHeaderID"));

                    b.Property<int>("MainCategoryID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryHeaderID");

                    b.HasIndex("MainCategoryID");

                    b.ToTable("CategoryHeader");
                });

            modelBuilder.Entity("FashionStore.Models.MainCategory", b =>
                {
                    b.Property<int>("MainCategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MainCategoryID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MainCategoryID");

                    b.ToTable("MainCategory");
                });

            modelBuilder.Entity("FashionStore.Models.Offer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Offers");
                });

            modelBuilder.Entity("FashionStore.Models.Order", b =>
                {
                    b.Property<int>("OrderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderID"));

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OrderID");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("FashionStore.Models.OrderItem", b =>
                {
                    b.Property<int>("OrderItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderItemID"));

                    b.Property<int>("OrderID")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("OrderItemID");

                    b.HasIndex("OrderID");

                    b.HasIndex("ProductID");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("FashionStore.Models.Product", b =>
                {
                    b.Property<int>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductID"));

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ProductID");

                    b.HasIndex("CategoryID");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            ProductID = 1037,
                            CategoryID = 3,
                            Description = "Regular Fit Printed Blue Sweatshirt for Men",
                            ImageUrl = "/images/sw_Mack JONNEY.jpg",
                            Name = "Mack JONNEY",
                            Price = 45m
                        },
                        new
                        {
                            ProductID = 1038,
                            CategoryID = 3,
                            Description = "Sweat Shirt Men's Jacket For Men Winter Wear Standard Length Thermal Insulation Sweatshirt",
                            ImageUrl = "/images/sw_Boldfit.jpg",
                            Name = "Boldfit",
                            Price = 48m
                        },
                        new
                        {
                            ProductID = 1039,
                            CategoryID = 3,
                            Description = "Cotton Design Printed Hooded Hoodies/Sweatshirts for Men & Women",
                            ImageUrl = "/images/sw_ADRO  .jpg",
                            Name = "ADRO ",
                            Price = 51m
                        },
                        new
                        {
                            ProductID = 1040,
                            CategoryID = 3,
                            Description = "Men Sweatshirts || Sweatshirts for Men || Unisex Sweatshirts ||Hoodie for Men || Unisex Hoodie || Hoodie",
                            ImageUrl = "/images/sw_JVX.jpg",
                            Name = "JVX",
                            Price = 56m
                        },
                        new
                        {
                            ProductID = 1041,
                            CategoryID = 3,
                            Description = "Solid Regular Fit Plain Casual Stylish Latest | Full Sleeve T Shirt for Men",
                            ImageUrl = "/images/sw_GRECIILOOKS .jpg",
                            Name = "GRECIILOOKS ",
                            Price = 102m
                        },
                        new
                        {
                            ProductID = 1042,
                            CategoryID = 3,
                            Description = "Men's Cotton Hooded Sweatshirt",
                            ImageUrl = "/images/sw_Alan Jones.jpg",
                            Name = "Alan Jones",
                            Price = 27m
                        },
                        new
                        {
                            ProductID = 1043,
                            CategoryID = 3,
                            Description = "Solid Round Neck Cotton Fleece Sweatshirt for Men",
                            ImageUrl = "/images/sw_Mack Jonney_1.jpg",
                            Name = "Mack Jonney",
                            Price = 28m
                        },
                        new
                        {
                            ProductID = 1044,
                            CategoryID = 3,
                            Description = "Half Zipper Solid Sweatshirt for Men (Pack of 2)",
                            ImageUrl = "/images/sw_Trillion.jpg",
                            Name = "Trillion",
                            Price = 98m
                        },
                        new
                        {
                            ProductID = 1045,
                            CategoryID = 3,
                            Description = "Clothing Men's Cotton Hooded Sweatshirt",
                            ImageUrl = "/images/sw_Alan Jones_1.jpg",
                            Name = "Alan Jones",
                            Price = 68m
                        },
                        new
                        {
                            ProductID = 1046,
                            CategoryID = 3,
                            Description = "Men's Full Sleeve Printed Sweatshirt for Men",
                            ImageUrl = "/images/sw_Trillion .jpg",
                            Name = "Trillion",
                            Price = 55m
                        },
                        new
                        {
                            ProductID = 1047,
                            CategoryID = 3,
                            Description = "Clothing Men's Fleece Hooded Hoodie",
                            ImageUrl = "/images/sw_Alan Jones_2.jpg",
                            Name = "Alan Jones",
                            Price = 14m
                        },
                        new
                        {
                            ProductID = 1048,
                            CategoryID = 3,
                            Description = "Trendy Front & Back Printed Fullsleeve Hooded Sweatshirt for Men",
                            ImageUrl = "/images/sw_BULLMER .jpg",
                            Name = "BULLMER",
                            Price = 59m
                        },
                        new
                        {
                            ProductID = 1049,
                            CategoryID = 4,
                            Description = "Men Denim Full Sleeve Regular Winter Jacket",
                            ImageUrl = "/images/J_KOTTY .jpg",
                            Name = "KOTTY",
                            Price = 68m
                        },
                        new
                        {
                            ProductID = 1050,
                            CategoryID = 4,
                            Description = "acket For Men Winter Wear Nylon Winter Standard Length Jacket For Men Minus Degree Jackets From Minus 10 Degree Winter Wear For Men Insulated Winter Jackets For Men Heavy Jackets",
                            ImageUrl = "/images/J_Boldfit.jpg",
                            Name = "Boldfit",
                            Price = 54m
                        },
                        new
                        {
                            ProductID = 1051,
                            CategoryID = 4,
                            Description = "Jacket for Men Quilted Hooded Winter Jackets for Men & Boys Full Sleeve Mens Jacket Monsoon Jackets for Men All Weather Jacket for Men Wear Bomber Jacket for Men, Jerkin for Men",
                            ImageUrl = "/images/J_Boldfit_1.jpg",
                            Name = "Boldfit",
                            Price = 21m
                        },
                        new
                        {
                            ProductID = 1052,
                            CategoryID = 4,
                            Description = "Men Polyester Jackets || Bomber Jacket For Men || Lightweight Outwear Sportswear Bomber Standard Length Jacket",
                            ImageUrl = "/images/J_Lymio.jpg",
                            Name = "Lymio",
                            Price = 47m
                        },
                        new
                        {
                            ProductID = 1053,
                            CategoryID = 4,
                            Description = "Men's Jacket",
                            ImageUrl = "/images/J_VOXATI.jpg",
                            Name = "VOXATI",
                            Price = 57m
                        },
                        new
                        {
                            ProductID = 1054,
                            CategoryID = 4,
                            Description = "For Men's Loopknit Full Sleeve Regular Fit Solid Bomber Jacket (Color Black)",
                            ImageUrl = "/images/J_LEOTUDE.jpg",
                            Name = "LEOTUDE CASUAL JACKET",
                            Price = 77m
                        },
                        new
                        {
                            ProductID = 1055,
                            CategoryID = 4,
                            Description = "Men's Black Faux Leather Jacket with Zipper, Multiple Pockets, and Removable Hood Design",
                            ImageUrl = "/images/J_Blaq Ash.jpg",
                            Name = "Blaq Ash",
                            Price = 112m
                        },
                        new
                        {
                            ProductID = 1056,
                            CategoryID = 5,
                            Description = "Casual, Formal, Party, Festive and Wedding Blazer, Single Breasted",
                            ImageUrl = "/images/M_B_HUMJOLI .jpg",
                            Name = "HUMJOLI",
                            Price = 54m
                        },
                        new
                        {
                            ProductID = 1057,
                            CategoryID = 5,
                            Description = "Men's Poly Viscose V-Shape Tuxedo Style Waistcoat",
                            ImageUrl = "/images/M_B_OORA.jpg",
                            Name = "OORA",
                            Price = 29m
                        },
                        new
                        {
                            ProductID = 1058,
                            CategoryID = 5,
                            Description = "Men's Slim Fit Single Breasted Blazer",
                            ImageUrl = "/images/M_B_MANQ.jpg",
                            Name = "MANQ",
                            Price = 63m
                        },
                        new
                        {
                            ProductID = 1059,
                            CategoryID = 5,
                            Description = "Tweed Blazer for Men - Formal & Casual Winter Wear Blazer",
                            ImageUrl = "/images/M_B_TAHVO.jpg",
                            Name = "TAHVO",
                            Price = 98m
                        },
                        new
                        {
                            ProductID = 1060,
                            CategoryID = 5,
                            Description = "Men’s Regular Fit Formal Blazer (Blue)",
                            ImageUrl = "/images/M_B_RISANI.jpg",
                            Name = "RISANI",
                            Price = 55m
                        },
                        new
                        {
                            ProductID = 1061,
                            CategoryID = 5,
                            Description = "Casual, Formal, Party, Festive and Wedding Blazer, Single Breasted",
                            ImageUrl = "/images/M_B_HUMJOLI_1.jpg",
                            Name = "HUMJOLI",
                            Price = 57m
                        },
                        new
                        {
                            ProductID = 1062,
                            CategoryID = 5,
                            Description = "Men Regular Fit Blazer",
                            ImageUrl = "/images/M_B_WINTAGE.jpg",
                            Name = "WINTAGE",
                            Price = 14m
                        },
                        new
                        {
                            ProductID = 1063,
                            CategoryID = 5,
                            Description = "Grey Bandgala Blazer with Hanky",
                            ImageUrl = "/images/M_B_TAHVO_1.jpg",
                            Name = "TAHVO",
                            Price = 25m
                        },
                        new
                        {
                            ProductID = 1064,
                            CategoryID = 5,
                            Description = "Men's Regular Blazer",
                            ImageUrl = "/images/M_B_Peter England.jpg",
                            Name = "Peter England",
                            Price = 95m
                        },
                        new
                        {
                            ProductID = 1065,
                            CategoryID = 5,
                            Description = "Men's Regular Fit Blazer",
                            ImageUrl = "/images/M_B_Van Heusen.jpg",
                            Name = "Van Heusen",
                            Price = 96m
                        },
                        new
                        {
                            ProductID = 1066,
                            CategoryID = 5,
                            Description = "Law Firm Men's Blazer Black Coat Latest Stylish Perfect Single Breasted Regular Fit Advocate Blazer for Casual Formal Office Wear",
                            ImageUrl = "/images/M_B_Gwalior.jpg",
                            Name = "Gwalior",
                            Price = 82m
                        },
                        new
                        {
                            ProductID = 1067,
                            CategoryID = 5,
                            Description = "Blazer for Men ",
                            ImageUrl = "/images/M_B_Luxrio.jpg",
                            Name = "Luxrio",
                            Price = 54m
                        },
                        new
                        {
                            ProductID = 1068,
                            CategoryID = 6,
                            Description = "Men's Casual Stretchable Denim Tapered Fit Carrot Jeans",
                            ImageUrl = "/images/M_Je_Ben Martin.jpg",
                            Name = "Ben Martin",
                            Price = 36m
                        },
                        new
                        {
                            ProductID = 1069,
                            CategoryID = 6,
                            Description = "Men's Slim Fit Washed Jeans Stretchable",
                            ImageUrl = "/images/M_Je_Urbano Fashion.jpg",
                            Name = "Urbano Fashion",
                            Price = 112m
                        },
                        new
                        {
                            ProductID = 1070,
                            CategoryID = 6,
                            Description = "Comfort Denim Jeans for Men Stretchable Jeans Pant Cotton Rich Jeans Casual Jeans Anti Odor | Anti Stain | Breathable",
                            ImageUrl = "/images/M_Je_PSS FASHION.jpg",
                            Name = "PSS FASHION'S",
                            Price = 94m
                        },
                        new
                        {
                            ProductID = 1071,
                            CategoryID = 6,
                            Description = "Men's 512 Slim Tapered Fit Mid Rise Jeans",
                            ImageUrl = "/images/M_Je_Levis.jpg",
                            Name = "Levi's ",
                            Price = 82m
                        },
                        new
                        {
                            ProductID = 1072,
                            CategoryID = 6,
                            Description = "Men's Classic Tapered Stretchable Twill Jeans",
                            ImageUrl = "/images/M_Je_Peter England.jpg",
                            Name = "Peter England",
                            Price = 87m
                        },
                        new
                        {
                            ProductID = 1073,
                            CategoryID = 6,
                            Description = "Men Jeans || Jeans for Men || Men Jeans Pants || Jeans Pant for Man",
                            ImageUrl = "/images/M_Je_QNIM.jpg",
                            Name = "QNIM",
                            Price = 57m
                        },
                        new
                        {
                            ProductID = 1074,
                            CategoryID = 6,
                            Description = "Men's Loose Jeans || Men's Jeans Pants || Denim Jeans || Baggy Jeans for Men ",
                            ImageUrl = "/images/M_Je_Lymio.jpg",
                            Name = "Lymio",
                            Price = 19m
                        },
                        new
                        {
                            ProductID = 1075,
                            CategoryID = 6,
                            Description = "Men Jeans || Relaxed Pants || Denim Baggy Jeans",
                            ImageUrl = "/images/M_Je_London Hills.jpg",
                            Name = "London Hills",
                            Price = 75m
                        },
                        new
                        {
                            ProductID = 1076,
                            CategoryID = 6,
                            Description = "Men's Slim Fit Jeans",
                            ImageUrl = "/images/M_Je_Sf Jeans By Pantaloons.jpg",
                            Name = "Sf Jeans By Pantaloons",
                            Price = 28m
                        },
                        new
                        {
                            ProductID = 1077,
                            CategoryID = 6,
                            Description = "Men Solid Stretchable Blue Tapered Slim Fit Light Fade Midrise Jeans",
                            ImageUrl = "/images/M_Je_Everblue.jpg",
                            Name = "Everblue",
                            Price = 65m
                        },
                        new
                        {
                            ProductID = 1078,
                            CategoryID = 6,
                            Description = "Men Loose Fit Men's Flip Pocket Cargo || Men's Stylish Cotton Loose Fit Denim Cargo Jeans || Multi-Pocket Styling || Perfect for Casual Fashion || Comfortable Classic Men's Outerwear ",
                            ImageUrl = "/images/M_Je_TAGAS.jpg",
                            Name = "TAGAS",
                            Price = 39m
                        },
                        new
                        {
                            ProductID = 1079,
                            CategoryID = 6,
                            Description = "Men's Relaxed Jeans",
                            ImageUrl = "/images/M_Je_Lee.jpg",
                            Name = "Lee",
                            Price = 76m
                        },
                        new
                        {
                            ProductID = 1080,
                            CategoryID = 7,
                            Description = "Casual Regular Fit Trouser For Men",
                            ImageUrl = "/images/7_ENDEAVOUR.jpg",
                            Name = "ENDEAVOUR",
                            Price = 102m
                        },
                        new
                        {
                            ProductID = 1081,
                            CategoryID = 7,
                            Description = "Men's Solid Lycra Slim Fit Stretchable Casual Wear Comfortable Formal Trousers Pants Model 25.5 PantLycra COMBO3",
                            ImageUrl = "/images/7_Generic.jpg",
                            Name = "Generic",
                            Price = 19m
                        },
                        new
                        {
                            ProductID = 1082,
                            CategoryID = 7,
                            Description = "Men's Cargo Pants | Corduroy Trousers for Men Loose Fit | Cargos for Men | Men Cargo Trouser",
                            ImageUrl = "/images/7_Vogaan.jpg",
                            Name = "Vogaan",
                            Price = 48m
                        },
                        new
                        {
                            ProductID = 1083,
                            CategoryID = 7,
                            Description = "Men's Premium Polycotton Causal Baggy Fit Jogger || Lightweight & Flexible Elastic Waist with Drawstring || Wrinkle-Free Comfortable Trouser Pant for Summer",
                            ImageUrl = "/images/7_SMOWKLY.jpg",
                            Name = "SMOWKLY",
                            Price = 48m
                        },
                        new
                        {
                            ProductID = 1084,
                            CategoryID = 7,
                            Description = "Men's Regular Fit Dress Trousers, Formal Business Pants, Straight Leg",
                            ImageUrl = "/images/7_AXOLOTL.jpg",
                            Name = "AXOLOTL",
                            Price = 46m
                        },
                        new
                        {
                            ProductID = 1085,
                            CategoryID = 7,
                            Description = "Men's Slim Fit Formal Trousers with Mid-Rise Waist and Lycra Blend | Solid Pattern and Button Closure | Ideal for Office, Business, and Everyday Wear",
                            ImageUrl = "/images/7_BLACK SAND.jpg",
                            Name = "BLACK SAND",
                            Price = 67m
                        },
                        new
                        {
                            ProductID = 1086,
                            CategoryID = 7,
                            Description = "Men Cargo || Men Cargo Pants || Men Cargo Pants Cotton || Cargos for Men",
                            ImageUrl = "/images/7_Louis Philippe.jpg",
                            Name = "Louis Philippe",
                            Price = 45m
                        },
                        new
                        {
                            ProductID = 1087,
                            CategoryID = 7,
                            Description = "Slim Fit Solid Superior Comfort with Extra Stretch Trouser",
                            ImageUrl = "/images/7_Louis Philippe.jpg",
                            Name = "Louis Philippe",
                            Price = 48m
                        },
                        new
                        {
                            ProductID = 1088,
                            CategoryID = 7,
                            Description = "Cargo for Men | Men Cargo Pants | Men Cargo Pants Cotton | Men Cargo | Trousers for Men | Baggy Cargo Pants for Men | Cargos for Men",
                            ImageUrl = "/images/7_GRECIILOOKS.jpg",
                            Name = "GRECIILOOKS",
                            Price = 51m
                        },
                        new
                        {
                            ProductID = 1089,
                            CategoryID = 7,
                            Description = "Men's Formal Trousers || Slim Fit Men's Wear Trousers || Stretchable Formal Pant Trousers || Trouser for Men",
                            ImageUrl = "/images/7_TOPLOT.jpg",
                            Name = "TOPLOT",
                            Price = 56m
                        },
                        new
                        {
                            ProductID = 1090,
                            CategoryID = 7,
                            Description = "Men Cargo || Men Cargo Pants || Men Cargo Pants Cotton || Cargos for Men",
                            ImageUrl = "/images/7_Lymio.jpg",
                            Name = "Lymio",
                            Price = 102m
                        },
                        new
                        {
                            ProductID = 1091,
                            CategoryID = 8,
                            Description = "Shorts for Men Gym Half Pants for Men & Boys Training Mens Shorts Quick Dry Men Shorts for Workout & Home Wear Lightweight Gym Shorts for Men Gym Wear for Men Sports Shorts for Men",
                            ImageUrl = "/images/8_Boldfit.jpg",
                            Name = "Boldfit",
                            Price = 27m
                        },
                        new
                        {
                            ProductID = 1092,
                            CategoryID = 8,
                            Description = "Men's Super Combed Cotton Rich Regular Fit Solid Shorts with Side Pockets",
                            ImageUrl = "/images/8_Jockey.jpg",
                            Name = "Jockey",
                            Price = 28m
                        },
                        new
                        {
                            ProductID = 1093,
                            CategoryID = 8,
                            Description = "Men's Cotton Shorts | Shorts for Mens | Mens Shorts",
                            ImageUrl = "/images/8_DOBAD.jpg",
                            Name = "DOBAD",
                            Price = 48m
                        },
                        new
                        {
                            ProductID = 1094,
                            CategoryID = 8,
                            Description = "Men Shorts || Men Shorts Cotton || Men Shorts Casual",
                            ImageUrl = "/images/8_Lymio.jpg",
                            Name = "Lymio",
                            Price = 68m
                        },
                        new
                        {
                            ProductID = 1095,
                            CategoryID = 8,
                            Description = "Men's Solid Cotton Shorts ",
                            ImageUrl = "/images/8_TAGDO.jpg",
                            Name = "TAGDO",
                            Price = 55m
                        },
                        new
                        {
                            ProductID = 1096,
                            CategoryID = 8,
                            Description = "Men's Cotton Boxer Shorts Regular Fit Solid Shorts",
                            ImageUrl = "/images/8_Pepe Jeans.jpg",
                            Name = "Pepe Jeans",
                            Price = 14m
                        },
                        new
                        {
                            ProductID = 1097,
                            CategoryID = 8,
                            Description = "Men's Regular Fit Shorts with Pocket Multicolor",
                            ImageUrl = "/images/8_0-DEGREE.jpg",
                            Name = "0-DEGREE",
                            Price = 59m
                        },
                        new
                        {
                            ProductID = 1098,
                            CategoryID = 8,
                            Description = "Men Casual Shorts",
                            ImageUrl = "/images/8_U.S. POLO ASSN.jpg",
                            Name = "U.S. POLO ASSN",
                            Price = 68m
                        },
                        new
                        {
                            ProductID = 1099,
                            CategoryID = 9,
                            Description = "Men's Oversized Cargo Utility Joggers",
                            ImageUrl = "/images/9_NOBERO.jpg",
                            Name = "NOBERO",
                            Price = 54m
                        },
                        new
                        {
                            ProductID = 1100,
                            CategoryID = 9,
                            Description = "Men's Track Pant with Lycra Elastic Jogger Suitable for Active Wear | Jogger Yoga Wear, Sports",
                            ImageUrl = "/images/9_U GENIUS SPORTS.jpg",
                            Name = "U GENIUS SPORTS",
                            Price = 21m
                        },
                        new
                        {
                            ProductID = 1101,
                            CategoryID = 9,
                            Description = "Men Slim Fit Joggers for Men for Running, Gym Sports Lower for Men & Boys Summer Track Pants for Men",
                            ImageUrl = "/images/9_Boldfit.jpg",
                            Name = "Boldfit",
                            Price = 47m
                        },
                        new
                        {
                            ProductID = 1102,
                            CategoryID = 9,
                            Description = "Men Joggers ||Track Pant for Men || Men Joggers || Printed Joggers",
                            ImageUrl = "/images/9_Lymio.jpg",
                            Name = "Lymio",
                            Price = 57m
                        },
                        new
                        {
                            ProductID = 1103,
                            CategoryID = 9,
                            Description = "Men Regular Fit Track Pants",
                            ImageUrl = "/images/9_U.S. POLO ASSN.jpg",
                            Name = "U.S. POLO ASSN",
                            Price = 77m
                        },
                        new
                        {
                            ProductID = 1104,
                            CategoryID = 9,
                            Description = "Men's Track Pant with Lycra Elastic Jogger Suitable for Active Wear",
                            ImageUrl = "/images/9_Mehrang.jpg",
                            Name = "Mehrang",
                            Price = 112m
                        },
                        new
                        {
                            ProductID = 1105,
                            CategoryID = 10,
                            Description = "Mens 3392 Causal Shoes | Loafers | Moccasins | Lighweight Slip-On's | Soft Cushioned Insole | Trendy Non Lace-up Deisgn",
                            ImageUrl = "/images/10_Centrino.jpg",
                            Name = "Centrino",
                            Price = 54m
                        },
                        new
                        {
                            ProductID = 1106,
                            CategoryID = 10,
                            Description = "Mens I-and Laceup Casual Shoes",
                            ImageUrl = "/images/10_Bata.jpg",
                            Name = "Bata",
                            Price = 29m
                        },
                        new
                        {
                            ProductID = 1107,
                            CategoryID = 10,
                            Description = "Mens 3392 Causal Shoes | Loafers | Moccasins | Lighweight Slip-On's | Soft Cushioned Insole | Trendy Non Lace-up Deisgn | Stylish & Comfortable",
                            ImageUrl = "/images/10_Centrino_1.jpg",
                            Name = "Centrino",
                            Price = 63m
                        },
                        new
                        {
                            ProductID = 1108,
                            CategoryID = 10,
                            Description = "Men's Leather Casual Shoes",
                            ImageUrl = "/images/10_Woodland.jpg",
                            Name = "Woodland",
                            Price = 98m
                        },
                        new
                        {
                            ProductID = 1109,
                            CategoryID = 11,
                            Description = "Mens Stride Runner Running",
                            ImageUrl = "/images/11_Reebok.jpg",
                            Name = "Reebok",
                            Price = 55m
                        },
                        new
                        {
                            ProductID = 1110,
                            CategoryID = 11,
                            Description = "Mens Dazzler Sneaker",
                            ImageUrl = "/images/11_Puma.jpg",
                            Name = "Puma",
                            Price = 57m
                        },
                        new
                        {
                            ProductID = 1111,
                            CategoryID = 11,
                            Description = "Men Sport Shoes | Running Shoes | Casual Walking Shoes | Sneakers",
                            ImageUrl = "/images/11_BRUTON.jpg",
                            Name = "BRUTON",
                            Price = 14m
                        },
                        new
                        {
                            ProductID = 1112,
                            CategoryID = 11,
                            Description = "Mens Indus-251 Running Shoe",
                            ImageUrl = "/images/11_LANCER.jpg",
                            Name = "LANCER",
                            Price = 25m
                        },
                        new
                        {
                            ProductID = 1113,
                            CategoryID = 12,
                            Description = "Men's SFG 549 Flip-Flop",
                            ImageUrl = "/images/12_SPARX.jpg",
                            Name = "SPARX",
                            Price = 95m
                        },
                        new
                        {
                            ProductID = 1114,
                            CategoryID = 12,
                            Description = "Unisex Slide Max Slide",
                            ImageUrl = "/images/12_Puma.jpg",
                            Name = "Puma",
                            Price = 96m
                        },
                        new
                        {
                            ProductID = 1115,
                            CategoryID = 12,
                            Description = "Men's Rafa Sandal",
                            ImageUrl = "/images/12_U.S. POLO ASSN.jpg",
                            Name = "U.S. POLO ASSN",
                            Price = 82m
                        },
                        new
                        {
                            ProductID = 1116,
                            CategoryID = 12,
                            Description = "Men's Slip-On Slide Sandal",
                            ImageUrl = "/images/12_Woodland .jpg",
                            Name = "Woodland ",
                            Price = 54m
                        },
                        new
                        {
                            ProductID = 1117,
                            CategoryID = 13,
                            Description = "Bamboo Socks for Men | Ankle Length | Odour-Free & Breathable | Padded Base & Anti-bacterial | 3X Softer than Cotton Socks",
                            ImageUrl = "/images/13_HEELIUM.jpg",
                            Name = "HEELIUM",
                            Price = 36m
                        },
                        new
                        {
                            ProductID = 1118,
                            CategoryID = 13,
                            Description = "12 Pairs Solid Cotton Ankle Length Socks for Men & Women, Multicolor, Pack of 12, Free Size",
                            ImageUrl = "/images/13_SJeware.jpg",
                            Name = "SJeware",
                            Price = 112m
                        },
                        new
                        {
                            ProductID = 1119,
                            CategoryID = 13,
                            Description = "Men's Cotton Full Length Socks Free Size - Pack of 3",
                            ImageUrl = "/images/13_Peter England.jpg",
                            Name = "Peter England",
                            Price = 94m
                        },
                        new
                        {
                            ProductID = 1120,
                            CategoryID = 13,
                            Description = "Mens Cotton Ankle Length Socks (Pack of 3) Dark Grey, Navy, Black",
                            ImageUrl = "/images/13_Peter England_1.jpg",
                            Name = "Peter England",
                            Price = 82m
                        },
                        new
                        {
                            ProductID = 1121,
                            CategoryID = 14,
                            Description = "430 w/ 40mm Drivers, Beast Mode w/ 40ms Latency, 40hrs Playback, ENx Tech, Voice Assistant, BTv5.4, Adaptive Fit & Easy Access Controls, Bluetooth Over Ear Headphones(Black Sabre)",
                            ImageUrl = "/images/14_boAt Rockerz.jpg",
                            Name = "boAt Rockerz",
                            Price = 87m
                        },
                        new
                        {
                            ProductID = 1122,
                            CategoryID = 14,
                            Description = "Wireless Bluetooth Headphones with Mic, Up to 50Hrs Battery-Blue",
                            ImageUrl = "/images/14_Sony WH-CH520.jpg",
                            Name = "Sony WH-CH520",
                            Price = 57m
                        },
                        new
                        {
                            ProductID = 1123,
                            CategoryID = 14,
                            Description = "(1 Year Warranty Headset Bluetooth V5.0 with Mic and Noice Cancellation Feature | for Gym, Sports, Travelling and Driving Compatible with All Bluetooth Enabled Devices",
                            ImageUrl = "/images/14_Drumstone.jpg",
                            Name = "Drumstone",
                            Price = 19m
                        },
                        new
                        {
                            ProductID = 1124,
                            CategoryID = 14,
                            Description = "Active Noise Cancellation(~32dB), 120Hrs Battery, App Support, Crystal Bionic Sound, 4Mics ENx, v5.3 Bluetooth TWS in Ear Earbuds Wireless Earphones with mic (Crystal Black)",
                            ImageUrl = "/images/14_boAt Nirvana Ion ANC.jpg",
                            Name = "boAt Nirvana Ion ANC",
                            Price = 75m
                        },
                        new
                        {
                            ProductID = 1125,
                            CategoryID = 15,
                            Description = "Square 100% UV protected Sunglasses for Unisex",
                            ImageUrl = "/images/15_Fastrack.jpg",
                            Name = "Fastrack",
                            Price = 28m
                        },
                        new
                        {
                            ProductID = 1126,
                            CategoryID = 15,
                            Description = "3 Pack Polarized Sunglasses for Men Lightweight Sun Glasses with UV Protection for Driving Fishing Golf",
                            ImageUrl = "/images/15_Rocf Rossini.jpg",
                            Name = "Rocf Rossini",
                            Price = 65m
                        },
                        new
                        {
                            ProductID = 1127,
                            CategoryID = 15,
                            Description = "Unbreakable TR90 Polarized SPORTS SUNGLASSES - Chopper HD Clear Vision Motorcycle Riding Running Biking (Black)",
                            ImageUrl = "/images/15_ELEGANTE.jpg",
                            Name = "ELEGANTE",
                            Price = 39m
                        },
                        new
                        {
                            ProductID = 1128,
                            CategoryID = 15,
                            Description = "Unisex Combo offer pack of 4 shades glasses White Black Candy MC stan Rectangular Retro Vintage Narrow Non-Polarized Sunglasses Small Narrow Square Sun Glasses Combo offer pack (Medium)",
                            ImageUrl = "/images/15_Sheomy.jpg",
                            Name = "Sheomy",
                            Price = 76m
                        },
                        new
                        {
                            ProductID = 1129,
                            CategoryID = 16,
                            Description = "Women Cotton Tiered Printed Maxi Dress",
                            ImageUrl = "/images/16_BIBA.jpg",
                            Name = "BIBA",
                            Price = 102m
                        },
                        new
                        {
                            ProductID = 1130,
                            CategoryID = 16,
                            Description = "Floral Printed Smocked Tiered Dress | Maxi Dress with Square Neck",
                            ImageUrl = "/images/16_DRAPE AND DAZZLE.jpg",
                            Name = "DRAPE AND DAZZLE",
                            Price = 19m
                        },
                        new
                        {
                            ProductID = 1131,
                            CategoryID = 16,
                            Description = "Women's Rayon Viscose Anarkali Printed Kurta with Palazzo & Dupatta",
                            ImageUrl = "/images/16_GoSriKi.jpg",
                            Name = "GoSriKi",
                            Price = 48m
                        },
                        new
                        {
                            ProductID = 1132,
                            CategoryID = 16,
                            Description = "Dress for Women Printed Midi Dress with V-Neck, Puffed Sleeves",
                            ImageUrl = "/images/16_flowervelly.jpg",
                            Name = "flowervelly",
                            Price = 48m
                        },
                        new
                        {
                            ProductID = 1133,
                            CategoryID = 16,
                            Description = "Rayon Fit and Flare Below The Knee One Piece Dresses for Women | Dress",
                            ImageUrl = "/images/16_GRECIILOOKS.jpg",
                            Name = "GRECIILOOKS",
                            Price = 46m
                        },
                        new
                        {
                            ProductID = 1134,
                            CategoryID = 16,
                            Description = "Women Knee Length Dress",
                            ImageUrl = "/images/16_Max.jpg",
                            Name = "Max",
                            Price = 67m
                        },
                        new
                        {
                            ProductID = 1135,
                            CategoryID = 16,
                            Description = "Fashion Dress | Knee Length | Half Sleeve | Summer Dress | Casual Wear Dress for Women",
                            ImageUrl = "/images/16_Leriya.jpg",
                            Name = "Leriya",
                            Price = 78m
                        },
                        new
                        {
                            ProductID = 1136,
                            CategoryID = 16,
                            Description = "Women's Floral Printed Cotton Flared Maxi Dress (Drspinkkinnu_Baby Pink)",
                            ImageUrl = "/images/16_Stylum.jpg",
                            Name = "Stylum",
                            Price = 102m
                        },
                        new
                        {
                            ProductID = 1137,
                            CategoryID = 16,
                            Description = "Women coords Set | Women Cord Sets Stylish Short | 2 Piece Set for Women | Women Cord Sets Stylish Western | Cord Set for Women | Women Cord Sets",
                            ImageUrl = "/images/16_London Hills.jpg",
                            Name = "London Hills",
                            Price = 45m
                        },
                        new
                        {
                            ProductID = 1138,
                            CategoryID = 16,
                            Description = "Solid Halter Neck Solid Bodycon Midi Dress for Women's & Girl's",
                            ImageUrl = "/images/16_Aahwan.jpg",
                            Name = "Aahwan",
                            Price = 102m
                        },
                        new
                        {
                            ProductID = 1139,
                            CategoryID = 16,
                            Description = "Women Fancy Plain & Solid Designer Dress for Women",
                            ImageUrl = "/images/16_AASK.jpg",
                            Name = "AASK",
                            Price = 12m
                        },
                        new
                        {
                            ProductID = 1140,
                            CategoryID = 16,
                            Description = "Women's Polyester Shift Mini Dress",
                            ImageUrl = "/images/16_VERO MODA.jpg",
                            Name = "VERO MODA",
                            Price = 36m
                        },
                        new
                        {
                            ProductID = 1141,
                            CategoryID = 16,
                            Description = "Vertical Striped Pattern | Short-Sleeve | Casual Wear | Dress with Tie | Summer Dress for Women",
                            ImageUrl = "/images/16_Leriya Fashion.jpg",
                            Name = "Leriya Fashion",
                            Price = 65m
                        },
                        new
                        {
                            ProductID = 1142,
                            CategoryID = 16,
                            Description = "Dress for Woman - Short Dress & Long Dress Latest Stylish Unique Border Design and Tassel Stretchable with Adjustable Drawstring fit and Flare",
                            ImageUrl = "/images/16_KE KANHA EXPORTS.jpg",
                            Name = "KE KANHA EXPORTS",
                            Price = 59m
                        },
                        new
                        {
                            ProductID = 1143,
                            CategoryID = 16,
                            Description = "TASHVIKA'S Women's Skater Knee Length Dress",
                            ImageUrl = "/images/16_TASHVIKA.jpg",
                            Name = "TASHVIKA",
                            Price = 74m
                        },
                        new
                        {
                            ProductID = 1144,
                            CategoryID = 16,
                            Description = "Women's Lyocell Casual Solid Full Sleeve Collared Top and Pant Set with Blazer | Western Set for Women",
                            ImageUrl = "/images/16_House of Jangid.jpg",
                            Name = "House of Jangid",
                            Price = 54m
                        },
                        new
                        {
                            ProductID = 1145,
                            CategoryID = 16,
                            Description = "Solid Striped Backless Side Slit Dress Backless Dress for Women's & Girl's",
                            ImageUrl = "/images/16_Aahwan_1.jpg",
                            Name = "Aahwan",
                            Price = 86m
                        },
                        new
                        {
                            ProductID = 1146,
                            CategoryID = 16,
                            Description = "Dresses for Women|One Piece Dress for Women|Western Dress for Women",
                            ImageUrl = "/images/16_TOPLOT.jpg",
                            Name = "TOPLOT",
                            Price = 23m
                        },
                        new
                        {
                            ProductID = 1147,
                            CategoryID = 17,
                            Description = "Women's Casual Printed Round Neck, Oversized Longline Drop Shoulder Boho Style T-Shirt",
                            ImageUrl = "/images/17_TQH.jpg",
                            Name = "TQH",
                            Price = 67m
                        },
                        new
                        {
                            ProductID = 1148,
                            CategoryID = 17,
                            Description = "Women's Cotton Blend Full Sleeves Round Neck Printed T-Shirt | Combo of 2 Stylish & Comfortable Tees | Soft & Breathable Fabric | Casual Purple&Pink",
                            ImageUrl = "/images/17_LEEBURG.jpg",
                            Name = "LEEBURG",
                            Price = 45m
                        },
                        new
                        {
                            ProductID = 1149,
                            CategoryID = 17,
                            Description = "Training T Shirt for Women Cropped Tshirt for Women Relax Fit T Shirts for Women for Active Wear, Workout Quick Dry Gym Wear for Women Running Regular Fit T-Shirts for Women Short T Shirt",
                            ImageUrl = "/images/17_Boldfit.jpg",
                            Name = "Boldfit",
                            Price = 44m
                        },
                        new
                        {
                            ProductID = 1150,
                            CategoryID = 17,
                            Description = "Women's Print Oversized T-Shirt | Cotton Blend | Casual Loose Fit | S-XL | Trendy Graphic Tee",
                            ImageUrl = "/images/17_KOTTY.jpg",
                            Name = "KOTTY",
                            Price = 55m
                        },
                        new
                        {
                            ProductID = 1151,
                            CategoryID = 17,
                            Description = "Oversized Cottonblend Half Sleeve Round Neck Longline Drop Shoulder, Colorful Printed T-Shirt Women's Combo T-Shirts (Pack of 3)",
                            ImageUrl = "/images/17_LEOTUDE.jpg",
                            Name = "LEOTUDE",
                            Price = 66m
                        },
                        new
                        {
                            ProductID = 1152,
                            CategoryID = 17,
                            Description = "Women's Regular Fit T-Shirt",
                            ImageUrl = "/images/17_Max.jpg",
                            Name = "Max",
                            Price = 77m
                        },
                        new
                        {
                            ProductID = 1153,
                            CategoryID = 17,
                            Description = "Fashion Women Tops | Tops for Women | Regular Fit Tops for Jeans for Women | Korean Tops for Women | Trendy Tops for Women | Western Tops for Women Stylish",
                            ImageUrl = "/images/17_Leriya.jpg",
                            Name = "Leriya",
                            Price = 88m
                        },
                        new
                        {
                            ProductID = 1154,
                            CategoryID = 17,
                            Description = "Women Regular Fit Tops | Tops for Women | Tops for Jeans for Women | Korean Tops for Women | Tops for Women | Western Tops for Women Stylish",
                            ImageUrl = "/images/17_GRECIILOOKS.jpg",
                            Name = "GRECIILOOKS",
                            Price = 99m
                        },
                        new
                        {
                            ProductID = 1155,
                            CategoryID = 17,
                            Description = "Women Printed Round Neck Oversized T-Shirt | Loose Fit Drop Shoulder T-Shirt Pack of 3",
                            ImageUrl = "/images/17_London Hills.jpg",
                            Name = "London Hills",
                            Price = 25m
                        },
                        new
                        {
                            ProductID = 1156,
                            CategoryID = 18,
                            Description = "Fashion Waffle Women's Cotton Solid Half Sleeve Round Neck T-Shirt",
                            ImageUrl = "/images/18_Urvi.jpg",
                            Name = "Urvi",
                            Price = 63m
                        },
                        new
                        {
                            ProductID = 1157,
                            CategoryID = 18,
                            Description = "Women Regular Fit Tops | Tops for Women | Tops for Jeans for Women | Korean Tops for Women | Tops for Women | Western Tops for Women Stylish",
                            ImageUrl = "/images/18_GRECIILOOKS.jpg",
                            Name = "GRECIILOOKS",
                            Price = 37m
                        },
                        new
                        {
                            ProductID = 1158,
                            CategoryID = 18,
                            Description = "Graphic Women's Casual T-Shirt – Premium Cotton Printed Tee for Women | Stylish & Comfortable White T-Shirt",
                            ImageUrl = "/images/18_Mr Trending.jpg",
                            Name = "Mr Trending",
                            Price = 81m
                        },
                        new
                        {
                            ProductID = 1159,
                            CategoryID = 18,
                            Description = "Women's Casual Puff Sleeves Floral Print Peplum Top",
                            ImageUrl = "/images/18_Sheetal.jpg",
                            Name = "Sheetal",
                            Price = 95m
                        },
                        new
                        {
                            ProductID = 1160,
                            CategoryID = 18,
                            Description = "Women's Regular Fit Top",
                            ImageUrl = "/images/18_DEIDAD.jpg",
                            Name = "DEIDAD",
                            Price = 76m
                        },
                        new
                        {
                            ProductID = 1161,
                            CategoryID = 18,
                            Description = "Women's Korean Style Knitted Sheer Crochet Long Sleeve Hollow Out Colour Block Print Crop Top T-Shirt Sweater",
                            ImageUrl = "/images/18_ICW .jpg",
                            Name = "ICW ",
                            Price = 46m
                        },
                        new
                        {
                            ProductID = 1162,
                            CategoryID = 18,
                            Description = "Women's Printed Rayon Shirt Top for Women | Western Shirt for Women Stylish Latest | Office Wear Crop Top Blouse",
                            ImageUrl = "/images/18_Bollyclues.jpg",
                            Name = "Bollyclues",
                            Price = 35m
                        },
                        new
                        {
                            ProductID = 1163,
                            CategoryID = 18,
                            Description = "Women's Regular Top",
                            ImageUrl = "/images/18_rytras.jpg",
                            Name = "rytras",
                            Price = 102m
                        },
                        new
                        {
                            ProductID = 1164,
                            CategoryID = 19,
                            Description = "Women’s High-Rise Straight Fit Jeans | Stretchable Cotton Lycra Denim | Stylish & Comfortable Casual Wear ",
                            ImageUrl = "/images/19_FRENCH ROSE.jpg",
                            Name = "FRENCH ROSE",
                            Price = 78m
                        },
                        new
                        {
                            ProductID = 1165,
                            CategoryID = 19,
                            Description = "Women Cotton Solid Mid-Rise Super Flared Jeans",
                            ImageUrl = "/images/19_Globus.jpg",
                            Name = "Globus",
                            Price = 65m
                        },
                        new
                        {
                            ProductID = 1166,
                            CategoryID = 19,
                            Description = "Women's Mid Rise 80s Mom Tapered Jeans",
                            ImageUrl = "/images/19_Levi's.jpg",
                            Name = "Levi's",
                            Price = 94m
                        },
                        new
                        {
                            ProductID = 1167,
                            CategoryID = 19,
                            Description = "Women's Cotton Blend Stretchable Mid Rise Jeans",
                            ImageUrl = "/images/19_Nifty.jpg",
                            Name = "Nifty",
                            Price = 23m
                        },
                        new
                        {
                            ProductID = 1168,
                            CategoryID = 19,
                            Description = "High Rise Dark Wash Cotton Relaxed Fit Women's Jeans",
                            ImageUrl = "/images/19_Pepe Jeans.jpg",
                            Name = "Pepe Jeans",
                            Price = 22m
                        },
                        new
                        {
                            ProductID = 1169,
                            CategoryID = 19,
                            Description = "Women's 100% Cotton Solid Wide Leg Jeans",
                            ImageUrl = "/images/19_Bewakoof.jpg",
                            Name = "Bewakoof",
                            Price = 35m
                        },
                        new
                        {
                            ProductID = 1170,
                            CategoryID = 19,
                            Description = "Women Skinny Fit Mid-Rise Jeans",
                            ImageUrl = "/images/19_KETCH.jpg",
                            Name = "KETCH",
                            Price = 56m
                        },
                        new
                        {
                            ProductID = 1171,
                            CategoryID = 20,
                            Description = "Women's Cotton Printed Night Suit Set of Top & Shorts",
                            ImageUrl = "/images/20_KSHS.jpg",
                            Name = "KSHS",
                            Price = 102m
                        },
                        new
                        {
                            ProductID = 1172,
                            CategoryID = 20,
                            Description = "Women's Cotton Shorts | Shorts for Women Night Wear | Sports and Running Shorts for Women | Gym Workout and Yoga Shorts | Women Shorts | Regular Fit Shorts for Women Combo (Pack of 2)",
                            ImageUrl = "/images/20_Fflirtygo.jpg",
                            Name = "Fflirtygo",
                            Price = 45m
                        },
                        new
                        {
                            ProductID = 1173,
                            CategoryID = 20,
                            Description = "Women 's Shorts - Plain",
                            ImageUrl = "/images/20_Splash.jpg",
                            Name = "Splash",
                            Price = 102m
                        },
                        new
                        {
                            ProductID = 1174,
                            CategoryID = 20,
                            Description = "Women's Relaxed Fit Mid Rise Highly Distressed Regular-Length Denim",
                            ImageUrl = "/images/20_Miss Chase.jpg",
                            Name = "Miss Chase",
                            Price = 12m
                        },
                        new
                        {
                            ProductID = 1175,
                            CategoryID = 20,
                            Description = "Womens Regular casual wear relax fit Shorts- pack of 3",
                            ImageUrl = "/images/20_Generic.jpg",
                            Name = "Generic",
                            Price = 36m
                        },
                        new
                        {
                            ProductID = 1176,
                            CategoryID = 20,
                            Description = "Women's Super Combed Cotton Relaxed Fit Sleep Shorts with Convenient Side Pockets",
                            ImageUrl = "/images/20_Jockey RX72.jpg",
                            Name = "Jockey RX72",
                            Price = 65m
                        },
                        new
                        {
                            ProductID = 1177,
                            CategoryID = 21,
                            Description = "Women's Multicolored Round Neck Short Sleeves Floral Waist Tie-Up Regular Length Jumpsuit",
                            ImageUrl = "/images/Miss Chase.jpg",
                            Name = "Miss Chase",
                            Price = 59m
                        },
                        new
                        {
                            ProductID = 1178,
                            CategoryID = 21,
                            Description = "Rayon Printed Jumpsuit for Women",
                            ImageUrl = "/images/21_FCV.jpg",
                            Name = "FCV",
                            Price = 74m
                        },
                        new
                        {
                            ProductID = 1179,
                            CategoryID = 21,
                            Description = "Women Jumpsuit",
                            ImageUrl = "/images/21_Indya.jpg",
                            Name = "Indya",
                            Price = 54m
                        },
                        new
                        {
                            ProductID = 1180,
                            CategoryID = 21,
                            Description = "Almond Beige Printed",
                            ImageUrl = "/images/21_W for Woman.jpg",
                            Name = "W for Woman",
                            Price = 86m
                        },
                        new
                        {
                            ProductID = 1181,
                            CategoryID = 21,
                            Description = "Fashion Women Co Ord Set for Women | Co Ord Set for Women Stylish | Festive Co Ord Set for Women | Travel Co Ord Set for Women | Half Sleeve Women Co-ord set",
                            ImageUrl = "/images/21_Leriya.jpg",
                            Name = "Leriya",
                            Price = 23m
                        },
                        new
                        {
                            ProductID = 1182,
                            CategoryID = 22,
                            Description = "Casual & Formal Single-Breasted Blazer Regular Fit Stylish Blazer for Womens",
                            ImageUrl = "/images/22_Fokashe Store.jpg",
                            Name = "Fokashe Store",
                            Price = 67m
                        },
                        new
                        {
                            ProductID = 1183,
                            CategoryID = 22,
                            Description = "Women's White Waist Coat-Sleeveless, Cotton Blend Waist Coat, Solid Single Breasted Waist Coat Boost Your Style For All Occusion For Girls & Women",
                            ImageUrl = "/images/22_Tandul.jpg",
                            Name = "Tandul",
                            Price = 45m
                        },
                        new
                        {
                            ProductID = 1184,
                            CategoryID = 22,
                            Description = "Women's Solid WaistCoat for Women V Neck Button Closure Sleeveless Waist Coat With Two Pockets Ladies Cord Western Party Casual Wear for Girls",
                            ImageUrl = "/images/22_DEEBACO.jpg",
                            Name = "DEEBACO",
                            Price = 44m
                        },
                        new
                        {
                            ProductID = 1185,
                            CategoryID = 22,
                            Description = "Witty Taupe Clean Front Blazer",
                            ImageUrl = "/images/22_Salt Attire.jpg",
                            Name = "Salt Attire",
                            Price = 55m
                        },
                        new
                        {
                            ProductID = 1186,
                            CategoryID = 22,
                            Description = "Women's Solid Relaxed Fit 3/4 Sleeve Co-ord Blazer and Trouser Set.",
                            ImageUrl = "/images/22_KOTTY.jpg",
                            Name = "KOTTY",
                            Price = 66m
                        },
                        new
                        {
                            ProductID = 1187,
                            CategoryID = 23,
                            Description = "Women's Stylish Flower Printed Palazzo Skirt (Black)-(Freesize)",
                            ImageUrl = "/images/23_Niue.jpg",
                            Name = "Niue",
                            Price = 77m
                        },
                        new
                        {
                            ProductID = 1188,
                            CategoryID = 23,
                            Description = "Women's Plus Size Solid Rayon Combo Loose Fit Skirt Palazzo Set - 2 PCS",
                            ImageUrl = "/images/23_Lastinch.jpg",
                            Name = "Lastinch",
                            Price = 88m
                        },
                        new
                        {
                            ProductID = 1189,
                            CategoryID = 23,
                            Description = "Rayon Gold Print Skirt Palazzo || Free Size || Rayon Palazzo || Skirt Palazzo || GOLDPRINT Skirt Palazzo || Multicolour",
                            ImageUrl = "/images/23_ENDFASHION.jpg",
                            Name = "ENDFASHION",
                            Price = 99m
                        },
                        new
                        {
                            ProductID = 1190,
                            CategoryID = 23,
                            Description = "Craft Women's High Cotton Waist Flared Knit Skart Short Stylish Skirt",
                            ImageUrl = "/images/23_NEOPOL.jpg",
                            Name = "NEOPOL",
                            Price = 25m
                        },
                        new
                        {
                            ProductID = 1191,
                            CategoryID = 23,
                            Description = "Mid Length Cotton Blend Skirt 113 Black",
                            ImageUrl = "/images/23_JANAK.jpg",
                            Name = "JANAK",
                            Price = 63m
                        },
                        new
                        {
                            ProductID = 1192,
                            CategoryID = 24,
                            Description = "Women's Full Sleeve Denim Jacket",
                            ImageUrl = "/images/24_FUNDAY FASHION.jpg",
                            Name = "FUNDAY FASHION",
                            Price = 37m
                        },
                        new
                        {
                            ProductID = 1193,
                            CategoryID = 24,
                            Description = "Long Winter Wear Velvet Jacket For Women",
                            ImageUrl = "/images/24_Leather.jpg",
                            Name = "Leather",
                            Price = 81m
                        },
                        new
                        {
                            ProductID = 1194,
                            CategoryID = 24,
                            Description = "Waterproof Unisex Rain Coat Hooded Full Sleeves Outdoor Men, Women, Boys & Girls Rainwear Poncho Raincoat for Camping, Hiking & Travelling",
                            ImageUrl = "/images/24_HACER EVA.jpg",
                            Name = "HACER EVA",
                            Price = 95m
                        },
                        new
                        {
                            ProductID = 1195,
                            CategoryID = 24,
                            Description = "Polycotton Jacket For Women | Women's Jacket | Long Jacket For Women | Jacket Tops For Women | Oversized Jacket For Standard Length Women",
                            ImageUrl = "/images/24_GRECIILOOKS.jpg",
                            Name = "GRECIILOOKS",
                            Price = 76m
                        },
                        new
                        {
                            ProductID = 1196,
                            CategoryID = 24,
                            Description = "Women's Leather Jacket for Winter, Zipper Front",
                            ImageUrl = "/images/24_JUGLYGIRLS.jpg",
                            Name = "JUGLYGIRLS",
                            Price = 46m
                        },
                        new
                        {
                            ProductID = 1197,
                            CategoryID = 25,
                            Description = "Women's Stylish Printed Cotton Saree for Party, Daily and Casual Wear",
                            ImageUrl = "/images/25_SRILOK.jpg",
                            Name = "SRILOK",
                            Price = 35m
                        },
                        new
                        {
                            ProductID = 1198,
                            CategoryID = 25,
                            Description = "Women's Shimmer Organza Sequence Embroidery Saree With Unstitched Blouse Piece",
                            ImageUrl = "/images/25_AKHILAM.jpg",
                            Name = "AKHILAM",
                            Price = 102m
                        },
                        new
                        {
                            ProductID = 1199,
                            CategoryID = 25,
                            Description = "Women's Silk Cotton Kalamkari Print Saree With Blouse Piece",
                            ImageUrl = "/images/25_EthnicJunction.jpg",
                            Name = "EthnicJunction",
                            Price = 78m
                        },
                        new
                        {
                            ProductID = 1200,
                            CategoryID = 25,
                            Description = "Women's Georgette Digital Printed Ready To Wear one Minute Saree With Unstitched Blouse Piece",
                            ImageUrl = "/images/25_Sidhidata.jpg",
                            Name = "Sidhidata",
                            Price = 65m
                        },
                        new
                        {
                            ProductID = 1201,
                            CategoryID = 25,
                            Description = "Women's Self Woven, Lace Georgette Saree with Unstitched Blouse",
                            ImageUrl = "/images/25_SIRIL.jpg",
                            Name = "SIRIL",
                            Price = 94m
                        },
                        new
                        {
                            ProductID = 1202,
                            CategoryID = 26,
                            Description = "Women's Brick Red & Dusty Green Boat Neck Sleeveless Self Design Lace Overlaid Regular Dress",
                            ImageUrl = "/images/26_Miss Chase.jpg",
                            Name = "Miss Chase",
                            Price = 23m
                        },
                        new
                        {
                            ProductID = 1203,
                            CategoryID = 26,
                            Description = "Women's Rayon Blend Straight Embroidered Kurta with Pant & Dupatta",
                            ImageUrl = "/images/26_GoSriKi .jpg",
                            Name = "GoSriKi ",
                            Price = 22m
                        },
                        new
                        {
                            ProductID = 1204,
                            CategoryID = 26,
                            Description = "Women's Yellow Faux Georgette Stitched Top with Dupatta Full Sleeve Embroidered Anarkali Gown",
                            ImageUrl = "/images/26_Miss Ethnik.jpg",
                            Name = "Miss Ethnik",
                            Price = 35m
                        },
                        new
                        {
                            ProductID = 1205,
                            CategoryID = 26,
                            Description = "short Kaftan for women's & girls unique border design and tassel stretchable adjustable drawstring free size western kaftan fit flared floral all seasons",
                            ImageUrl = "/images/26_KE KANHA EXPORTS .jpg",
                            Name = "KE KANHA EXPORTS",
                            Price = 56m
                        },
                        new
                        {
                            ProductID = 1206,
                            CategoryID = 26,
                            Description = "women'S Georgette Lehenga And Choli With Long Shrug Set For Solid With Heavy Embroidery Work Set",
                            ImageUrl = "/images/26_madhuram.jpg",
                            Name = "madhuram",
                            Price = 102m
                        });
                });

            modelBuilder.Entity("FashionStore.Models.Review", b =>
                {
                    b.Property<int>("ReviewID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReviewID"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReviewDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReviewerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ReviewID");

                    b.HasIndex("ProductID");

                    b.ToTable("Review");
                });

            modelBuilder.Entity("FashionStore.Models.WishlistItem", b =>
                {
                    b.Property<int>("WishlistItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WishlistItemID"));

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("WishlistItemID");

                    b.HasIndex("ProductID");

                    b.ToTable("WishlistItems");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("FashionStore.Models.CartItem", b =>
                {
                    b.HasOne("FashionStore.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("FashionStore.Models.Category", b =>
                {
                    b.HasOne("FashionStore.Models.CategoryHeader", "CategoryHeader")
                        .WithMany("Categories")
                        .HasForeignKey("CategoryHeaderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CategoryHeader");
                });

            modelBuilder.Entity("FashionStore.Models.CategoryHeader", b =>
                {
                    b.HasOne("FashionStore.Models.MainCategory", "MainCategory")
                        .WithMany("CategoryHeaders")
                        .HasForeignKey("MainCategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MainCategory");
                });

            modelBuilder.Entity("FashionStore.Models.OrderItem", b =>
                {
                    b.HasOne("FashionStore.Models.Order", null)
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FashionStore.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("FashionStore.Models.Product", b =>
                {
                    b.HasOne("FashionStore.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("FashionStore.Models.Review", b =>
                {
                    b.HasOne("FashionStore.Models.Product", "Product")
                        .WithMany("Reviews")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("FashionStore.Models.WishlistItem", b =>
                {
                    b.HasOne("FashionStore.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("FashionStore.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("FashionStore.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FashionStore.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("FashionStore.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FashionStore.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("FashionStore.Models.CategoryHeader", b =>
                {
                    b.Navigation("Categories");
                });

            modelBuilder.Entity("FashionStore.Models.MainCategory", b =>
                {
                    b.Navigation("CategoryHeaders");
                });

            modelBuilder.Entity("FashionStore.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("FashionStore.Models.Product", b =>
                {
                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
